### ISSUE TITLE
Attention avec les propriétés publiques dans les objets

### ISSUE THREAD

**Issue by technonerdz** [Evolution2626/Limelight-Test#6]
Il faudrait faire attention et essayer de ne pas avoir de propriété public dans les classes. Au lieu de mettre differentialDrive public, vous pourriez soit faire une fonction getDifferentialDrive dans Drivetrain qui retourne le differentialDrive, ou soit faire une fonction arcadeDrive dans Drivetrain qui appelerais la fonction differentialDrive.arcadeDrive. 

Comme ça, on s'assure que la classe est toujours en contrôle de ses propriétés et qu'ils ne peuvent pas être modifiés ailleurs.

https://github.com/Evolution2626/Limelight-Test/blob/27ec4875b7a6e5e8fdee6f30a9c9fec674911ecd/src/main/java/frc/robot/subsystems/Drivetrain.java#L22

https://github.com/Evolution2626/Limelight-Test/blob/27ec4875b7a6e5e8fdee6f30a9c9fec674911ecd/src/main/java/frc/robot/commands/AlignLimelightCommand.java#L28

**Comment by Zach3292** [comment]
j'ai enlevé le public et je l'ai remplacé par private, j'ai créé la function arcadeDrive pour y remédier
